New UI for mnemonic generation
trilogy-group/memorization-app pull request #131
Opened 2022-10-10 19:02 UTC by davidfortuoso-ti

2022-10-11 20:24 UTC, davidfortuoso-ti commented
Pending: 
- Use DB instead of external API
- Save mnemonics to DB
- Upload video PopUp

2022-10-13 06:11 UTC, kushal-ti requested changes

2022-10-13 06:11 UTC, kushal-ti commented on src/server/router/contentTree.ts
> +            "https://gshnf2p56bbinmx4na3lme4oce.appsync-api.us-west-2.amazonaws.com/graphql",
encode the API base url in constants.ts instead of hardcoding here

2022-10-13 06:11 UTC, kushal-ti commented on src/server/router/contentTree.ts
> +                "x-api-key": "da2-dlp6tok3uvhxrlow4jypfthabq",
likewise for the API key, don't hardcode here directly, use in a constants.ts

2022-10-13 07:59 UTC, davidfortuoso-ti commented on src/server/router/contentTree.ts
> +                "x-api-key": "da2-dlp6tok3uvhxrlow4jypfthabq",
[0e303a5](https://github.com/trilogy-group/memorization-app/pull/131/commits/0e303a52405eaee210c0afb2cb9fc5abadaa1ea6)

2022-10-13 08:09 UTC, merged